services:
  discord-bot:
    build: .
    container_name: discord-bot
    restart: always
    stdin_open: true
    tty: true
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - /app/node_modules
    environment:
      - TOKEN=${TOKEN}
      - APPLICATION_ID=${APPLICATION_ID}
      - PUBLIC_KEY=${PUBLIC_KEY}
      - BCDICE_API_URL=${BCDICE_API_URL}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - PERMISSION_INTEGER=${PERMISSION_INTEGER}
      - SERVER_PORT=${SERVER_PORT}
      - VOICEVOX_SERVER_URL=${VOICEVOX_SERVER_URL}
      - VOICE_SERVER_TEXT_LENGTH_LIMIT=${VOICE_SERVER_TEXT_LENGTH_LIMIT}
      - GUILD_CONFIGS_DIR=${GUILD_CONFIGS_DIR}
      - GUILD_DICTIONARIES_DIR=${GUILD_DICTIONARIES_DIR}
      - DEFAULT_SPEAKER_ENGINE=${DEFAULT_SPEAKER_ENGINE}
      - DEFAULT_SPEAKER_ID=${DEFAULT_SPEAKER_ID}
      - DEFAULT_SPEAKER_SPEED_SCALE=${DEFAULT_SPEAKER_SPEED_SCALE}
      - DEFAULT_SPEAKER_PITCH_SCALE=${DEFAULT_SPEAKER_PITCH_SCALE}
      - DEFAULT_SPEAKER_INTONATION_SCALE=${DEFAULT_SPEAKER_INTONATION_SCALE}
      - DEFAULT_SPEAKER_VOLUME_SCALE=${DEFAULT_SPEAKER_VOLUME_SCALE}
      - DEFAULT_SPEAKER_TEMPO_DYNAMICS_SCALE=${DEFAULT_SPEAKER_TEMPO_DYNAMICS_SCALE}
      - SPEAKER_SPEED_SCALE_UPPER_LIMIT=${SPEAKER_SPEED_SCALE_UPPER_LIMIT}
      - SPEAKER_SPEED_SCALE_LOWER_LIMIT=${SPEAKER_SPEED_SCALE_LOWER_LIMIT}
      - SPEAKER_PITCH_SCALE_UPPER_LIMIT=${SPEAKER_PITCH_SCALE_UPPER_LIMIT}
      - SPEAKER_PITCH_SCALE_LOWER_LIMIT=${SPEAKER_PITCH_SCALE_LOWER_LIMIT}
      - SPEAKER_INTONATION_SCALE_UPPER_LIMIT=${SPEAKER_INTONATION_SCALE_UPPER_LIMIT}
      - SPEAKER_INTONATION_SCALE_LOWER_LIMIT=${SPEAKER_INTONATION_SCALE_LOWER_LIMIT}
      - SPEAKER_VOLUME_SCALE_UPPER_LIMIT=${SPEAKER_VOLUME_SCALE_UPPER_LIMIT}
      - SPEAKER_VOLUME_SCALE_LOWER_LIMIT=${SPEAKER_VOLUME_SCALE_LOWER_LIMIT}
      - SPEAKER_TEMPO_DYNAMICS_SCALE_UPPER_LIMIT=${SPEAKER_TEMPO_DYNAMICS_SCALE_UPPER_LIMIT}
      - SPEAKER_TEMPO_DYNAMICS_SCALE_LOWER_LIMIT=${SPEAKER_TEMPO_DYNAMICS_SCALE_LOWER_LIMIT}
      - samplingRate=${samplingRate}
      - cooldownDuration=${cooldownDuration}
      - autocompleteLimit=${autocompleteLimit}
      - queueTimeout=${queueTimeout}
      - queuePollingInterval=${queuePollingInterval}
      - dictionaryEntryLimit=${dictionaryEntryLimit}
      - VOICE_READY_TIMEOUT=${VOICE_READY_TIMEOUT}
    depends_on:
      - voicevox

  voicevox:
    image: voicevox/voicevox_engine:cpu-ubuntu22.04-0.26.0-dev
    container_name: voicevox
    restart: always
    ports:
      - "50021:50021"
  